/**
 * dsh-openrouter-imagen — Host half.
 *
 * Generates images through the OpenRouter Image API (POST /api/v1/images) and
 * exposes them to two consumers:
 *
 *   - the model, through the `openrouter_generate_imagen` tool, whose result
 *     carries durable `image` content blocks;
 *   - the browser, through a same-origin JSON route under
 *     `/openrouter-imagen/api`, which the plugin's Client half calls with
 *     plain `fetch` (no Remote/typert surface is involved).
 *
 * Configuration lives in the `openrouter-imagen` settings namespace, so it
 * persists through the mounted settings provider (settings.yaml) and is
 * editable at runtime from Settings → 图像生成. `apiKey` is declared with
 * `role('secret')`, which keeps it out of every redacted settings protocol
 * response; this module never echoes it back to the browser either.
 *
 * Generated bytes are committed twice on purpose: as a durable attachment (the
 * only thing that makes a picture render in the conversation) and as a verbatim
 * file. The file goes into the calling session's own workspace — `saveDir`
 * under `exec.agent.session.header.cwd` — because that is where the project
 * that asked for it lives; a call with no workspace (or `saveDir` emptied)
 * falls back to the attachment store.
 *
 * Outbound HTTP goes through `undici` with an explicit proxy agent. Node's
 * global `fetch` ignores HTTP_PROXY/HTTPS_PROXY entirely (and the undici
 * package's `setGlobalDispatcher` cannot change that, because globalThis.fetch
 * runs on Node's internal copy of undici), so on a machine whose only route
 * out is a local proxy the global fetch silently takes a different network.
 * The resolution order below mirrors `dshmarket/lib/net.js`.
 *
 * @module dsh-openrouter-imagen
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { isAbsolute, join, relative } from 'node:path'
import Schema from '@deepseek-ai/schemastery'
import { defineTool } from '@deepseek-ai/dsh-tools'
import { EnvHttpProxyAgent, fetch as undiciFetch } from 'undici'

export const name = 'dsh-openrouter-imagen'

/** `settings` owns the namespace; `tools` receives the model-visible tool. */
export const inject = ['settings', 'tools']

const NS = 'openrouter-imagen'
/**
 * API root. Overridable so a deployment can point at a gateway or a local
 * stand-in, and so the offline pre-flight can assert the exact request body
 * against a mock server instead of a live account.
 */
const API_BASE = (process.env.OPENROUTER_IMAGE_API_BASE ?? '').trim() || 'https://openrouter.ai/api/v1'
const API_PATH = '/openrouter-imagen/api'
const MEDIA_EXT = { 'image/png': '.png', 'image/jpeg': '.jpg', 'image/webp': '.webp', 'image/gif': '.gif' }
const MAX_REFERENCES = 4
const MAX_INLINE_BYTES = 8000000
const REQUEST_TIMEOUT_MS = 600000
/** Default sub-folder, inside the session workspace, that holds generated files. */
const DEFAULT_SAVE_DIR = 'generated-images'

/** Settings namespace schema. Editable at runtime; `base` comes from the composition row. */
export const Config = Schema.object({
  apiKey: Schema.string().role('secret').default(''),
  model: Schema.string().default('google/gemini-2.5-flash-image'),
  resolution: Schema.string().default('1K'),
  aspectRatio: Schema.string().default('auto'),
  quality: Schema.string().default('auto'),
  outputFormat: Schema.string().default('png'),
  count: Schema.number().default(1),
  background: Schema.string().default('auto'),
  seed: Schema.string().default(''),
  providerSort: Schema.string().default(''),
  extraJson: Schema.string().default(''),
  saveDir: Schema.string().default(DEFAULT_SAVE_DIR),
})

/** Fields the browser may write. `apiKey` is write-only: an omitted or blank value leaves it untouched. */
const WRITABLE = [
  'apiKey',
  'model',
  'resolution',
  'aspectRatio',
  'quality',
  'outputFormat',
  'count',
  'background',
  'seed',
  'providerSort',
  'extraJson',
  'saveDir',
]

const SUGGESTED_MODELS = [
  'google/gemini-2.5-flash-image',
  'openai/gpt-image-1',
  'black-forest-labs/flux.2-pro',
  'bytedance-seed/seedream-4.5',
]

/* ------------------------------------------------------------------ *
 * Outbound HTTP (proxy aware)
 * ------------------------------------------------------------------ */

/** Resolve http/https proxy URLs the way undici's EnvHttpProxyAgent does, plus npm's config as a fallback. */
function proxyFromEnv() {
  const pick = (raw) => {
    const value = typeof raw === 'string' ? raw.trim() : ''
    if (value === '') return null
    return /^[a-z][a-z\d+.-]*:\/\//iu.test(value) ? value : `http://${value}`
  }
  const https = pick(process.env.https_proxy ?? process.env.HTTPS_PROXY) ?? pick(process.env.npm_config_https_proxy)
  const http = pick(process.env.http_proxy ?? process.env.HTTP_PROXY) ?? pick(process.env.npm_config_proxy)
  return { http, https }
}

/** Encode bytes as base64 without Buffer's per-call allocation churn. */
function toBase64(bytes) {
  return Buffer.from(bytes).toString('base64')
}

function errorMessage(error) {
  if (error === undefined || error === null) return '未知错误'
  if (typeof error === 'string') return error
  if (typeof error.message === 'string' && error.message.length > 0) return error.message
  return String(error)
}

function stamp() {
  const d = new Date()
  const pad = (n) => (n < 10 ? '0' + n : String(n))
  return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}`
}

/* ------------------------------------------------------------------ *
 * Plugin
 * ------------------------------------------------------------------ */

/**
 * Register the settings namespace, the model tool, and the browser API route.
 * @param ctx - Host context carrying `settings` and `tools`.
 * @param config - composition `base` layer for the settings namespace.
 */
export function apply(ctx, config = {}) {
  const scope = ctx.settings.register(NS, Config, { base: config })
  const readConfig = () => scope.get() ?? {}

  /**
   * The proxy pool belongs to this Fiber.
   *
   * A keep-alive agent built at module scope would survive unload and HMR and
   * leak its sockets into the next instance, so it is created lazily here and
   * closed by the disposer Cordis owns.
   */
  let proxyAgent = null
  ctx.effect(
    () => () => {
      const agent = proxyAgent
      proxyAgent = null
      if (agent !== null && typeof agent.close === 'function') void agent.close()
    },
    'openrouter-imagen: proxy agent',
  )

  /** Fetch through the proxy this machine is configured to use, or the plain global fetch when there is none. */
  async function httpFetch(url, init) {
    const { http, https } = proxyFromEnv()
    if (http === null && https === null) return await fetch(url, init)
    proxyAgent ??= new EnvHttpProxyAgent({ httpProxy: http ?? undefined, httpsProxy: https ?? undefined })
    return await undiciFetch(url, { ...init, dispatcher: proxyAgent })
  }

  /**
   * Reference images staged from the composer, consumed by the next successful
   * generation. Deliberately in memory: these are transient per-message inputs,
   * not configuration, and a multi-megabyte data URL has no business being
   * persisted into settings.yaml.
   */
  let pendingReferences = []

  /** One authenticated (or explicitly public) OpenRouter call. */
  async function callApi(path, payload, options) {
    const requireKey = !options || options.requireKey !== false
    const settings = readConfig()
    const key = String(settings.apiKey ?? '').trim()
    if (requireKey && key.length === 0) throw new Error('尚未设置 OpenRouter API Key（设置 → 图像生成）')

    const url = API_BASE + path
    const headers = { 'x-title': 'DSH-OpenRouter-Imagen' }
    if (key.length > 0) headers.authorization = `Bearer ${key}`
    // The caller's cancellation signal and this plugin's own ceiling are
    // combined: cancelling a turn has to abandon the paid provider request
    // rather than let it run to completion in the background.
    const timeout = AbortSignal.timeout(REQUEST_TIMEOUT_MS)
    const signal = options?.signal === undefined ? timeout : AbortSignal.any([options.signal, timeout])
    const init = { method: payload === undefined ? 'GET' : 'POST', headers, signal }
    if (payload !== undefined) {
      headers['content-type'] = 'application/json'
      init.body = JSON.stringify(payload)
    }

    let response
    try {
      response = await httpFetch(url, init)
    } catch (error) {
      if (error?.name === 'AbortError' || error?.name === 'TimeoutError') {
        throw new Error(error.name === 'TimeoutError' ? `生成请求超时（${Math.round(REQUEST_TIMEOUT_MS / 1000)} 秒）` : '生成请求已被取消')
      }
      throw new Error(`无法连接 OpenRouter（${proxyFromEnv().https ?? proxyFromEnv().http ?? '直连'}）：${errorMessage(error)}`)
    }
    const text = await response.text()
    let parsed = null
    try {
      parsed = JSON.parse(text)
    } catch {
      throw new Error(`OpenRouter 返回非 JSON 内容（HTTP ${response.status}）：${text.slice(0, 300)}`)
    }
    if (!response.ok) {
      const detail = parsed?.error?.message ?? JSON.stringify(parsed).slice(0, 400)
      if (response.status === 401) {
        throw new Error(`OpenRouter 401：API Key 缺失或无效（服务端原文：“${detail}”）。请确认 Key 以 sk-or-v1- 开头且未过期。`)
      }
      throw new Error(`OpenRouter HTTP ${response.status}：${detail}`)
    }
    return parsed
  }

  /** Collect reference image URLs from either shape the callers use. */
  function referenceUrls(source) {
    const urls = []
    const push = (value) => {
      if (urls.length < MAX_REFERENCES && typeof value === 'string' && value.length > 0) urls.push(value)
    }
    const structured = Array.isArray(source?.references) ? source.references : []
    for (const entry of structured) {
      if (typeof entry === 'string') {
        push(entry)
        continue
      }
      if (entry === null || typeof entry !== 'object') continue
      if (typeof entry.url === 'string') {
        push(entry.url)
        continue
      }
      if (typeof entry.data === 'string' && entry.data.length > 0) {
        const mediaType = typeof entry.mediaType === 'string' && entry.mediaType.length > 0 ? entry.mediaType : 'image/png'
        push(`data:${mediaType};base64,${entry.data}`)
      }
    }
    const listed = Array.isArray(source?.reference_images) ? source.reference_images : []
    for (const entry of listed) push(entry)
    return urls
  }

  /**
   * Draw the random seed for a seed box left empty.
   *
   * The value has to travel back to the caller (see `render` and the card's
   * 种子 chip): the whole point of a seed is being able to ask for the same
   * picture twice, and a number nobody learns cannot be asked for again.
   */
  function drawSeed() {
    return Math.floor(Math.random() * 2147483646) + 1
  }

  /** Assemble the /images request body from settings plus per-call overrides. */
  function buildBody(input) {
    const source = input ?? {}
    const settings = readConfig()
    const prompt = String(source.prompt ?? '').trim()
    if (prompt.length === 0) throw new Error('prompt 不能为空')
    const pick = (override, fallback) => {
      const value = override === undefined || override === null || override === '' ? fallback : override
      return value === undefined || value === null ? '' : String(value)
    }
    const model = pick(source.model, settings.model).trim()
    if (model.length === 0) throw new Error('未设置模型：请在设置中填写 OpenRouter 图像模型 id')

    const body = { model, prompt }
    const rawCount = source.count ?? settings.count
    const count = Number.isFinite(Number(rawCount)) ? Math.max(1, Math.min(10, Math.floor(Number(rawCount)))) : 1
    if (count > 1) body.n = count
    const resolution = pick(source.resolution, settings.resolution)
    if (resolution.length > 0 && resolution !== 'auto') body.resolution = resolution
    // The tool declares snake_case (`aspect_ratio`) while the panel config uses
    // camelCase; reading only the camel form silently dropped a per-call
    // override and quietly used the panel's value instead. Accept both.
    const aspect = pick(source.aspect_ratio ?? source.aspectRatio, settings.aspectRatio)
    if (aspect.length > 0 && aspect !== 'auto') body.aspect_ratio = aspect
    const quality = pick(source.quality, settings.quality)
    if (quality.length > 0 && quality !== 'auto') body.quality = quality
    const format = pick(source.output_format ?? source.outputFormat, settings.outputFormat)
    if (format.length > 0) body.output_format = format
    const background = pick(source.background, settings.background)
    if (background.length > 0 && background !== 'auto') body.background = background
    // `seed` is a string in settings (an empty box means "random") but a number
    // on the wire. An empty box does NOT mean "omit": OpenRouter only samples
    // deterministically for a seed it was actually given, so this plugin draws
    // the number itself and reports it back — determinism is per-provider, but a
    // seed that was sent is at least a seed that can be sent again.
    const seedText = pick(source.seed, settings.seed).trim()
    const seedRandom = seedText.length === 0
    let seedDrawn = null
    if (seedRandom) {
      seedDrawn = drawSeed()
    } else {
      const numeric = Number(seedText)
      if (!Number.isFinite(numeric)) throw new Error(`seed 必须是数字：${seedText}`)
      seedDrawn = Math.floor(numeric)
    }
    body.seed = seedDrawn
    if (String(settings.providerSort ?? '').length > 0) body.provider = { sort: settings.providerSort }

    const extra = String(settings.extraJson ?? '').trim()
    if (extra.length > 0) {
      let parsed
      try {
        parsed = JSON.parse(extra)
      } catch (error) {
        throw new Error(`附加参数不是合法 JSON：${errorMessage(error)}`)
      }
      if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error('附加参数必须是 JSON 对象')
      // A pass-through escape hatch, not a way to silently swap the model, the
      // prompt, or the staged reference images of a call that the panel and the
      // tool arguments already decided.
      for (const key of ['model', 'prompt', 'input_references']) {
        if (Object.prototype.hasOwnProperty.call(parsed, key)) throw new Error(`附加参数不能覆盖 ${key}：它由工具参数或「图像」面板决定`)
      }
      Object.assign(body, parsed)
    }

    // Per-call references win over staged ones, and the staged list is the
    // composer's contribution: the user pastes an image above the input box,
    // then asks for a generation without repeating the image in the prompt.
    const refs = referenceUrls(source).concat(pendingReferences).slice(0, MAX_REFERENCES)
    if (refs.length > 0) body.input_references = refs.map((url) => ({ type: 'image_url', image_url: { url } }))

    // `additionalParams` may override the seed; report what is actually sent.
    const seedSent = Number.isFinite(Number(body.seed)) ? Math.floor(Number(body.seed)) : seedDrawn
    // The conversation model cannot see the composer panel, so the values that
    // really reached the provider travel back with the result. Without this a
    // per-call override that failed to apply is indistinguishable from the
    // panel's own value, and the model reports the wrong parameters back.
    const params = {
      model: String(body.model ?? ''),
      count: Number.isFinite(Number(body.n)) ? Math.floor(Number(body.n)) : 1,
      resolution: body.resolution === undefined ? 'auto' : String(body.resolution),
      aspect_ratio: body.aspect_ratio === undefined ? 'auto' : String(body.aspect_ratio),
      quality: body.quality === undefined ? 'auto' : String(body.quality),
      output_format: body.output_format === undefined ? '' : String(body.output_format),
      background: body.background === undefined ? 'auto' : String(body.background),
      seed: seedSent,
      referenceCount: refs.length,
    }
    return { body, model, referenceCount: refs.length, seed: seedSent, seedRandom: seedSent === seedDrawn && seedRandom, params }
  }

  /**
   * Where a generated file actually lands.
   *
   * A picture asked for inside a project belongs in that project — next to the
   * code that will consume it — not in a hash-named directory under the DSH
   * home that the user then has to hunt for. So the session's own workspace
   * (`exec.agent.session.header.cwd`, the same root `read`/`write`/`edit`
   * resolve against) wins whenever there is one. `saveDir` is relative to it
   * unless absolute; an empty value opts out and keeps the old behaviour.
   *
   * @returns the absolute directory, or null when the attachment store is the
   *   right home (no workspace, opt-out, or an unwritable path).
   */
  async function projectDirectory(cwd) {
    const configured = String(readConfig().saveDir ?? '').trim()
    if (configured.length === 0) return null
    if (typeof cwd !== 'string' || cwd.length === 0) return null
    const base = isAbsolute(configured) ? configured : join(cwd, configured)
    try {
      await mkdir(base, { recursive: true })
      return base
    } catch (error) {
      console.warn(`[dsh-openrouter-imagen] cannot create ${base}: ${errorMessage(error)}`)
      return null
    }
  }

  /**
   * Write `bytes` under `dir` without ever overwriting an earlier call's file.
   *
   * Two generations in the same second produce the same timestamped name, and
   * silently replacing the previous picture is worse than an ugly suffix.
   */
  async function writeUnique(dir, name, bytes) {
    const dot = name.lastIndexOf('.')
    const stem = dot > 0 ? name.slice(0, dot) : name
    const ext = dot > 0 ? name.slice(dot) : ''
    for (let attempt = 0; attempt < 50; attempt += 1) {
      const candidate = join(dir, attempt === 0 ? name : `${stem}-${attempt + 1}${ext}`)
      try {
        await writeFile(candidate, bytes, { flag: 'wx' })
        return candidate
      } catch (error) {
        if (error?.code !== 'EEXIST') {
          console.warn(`[dsh-openrouter-imagen] cannot write ${candidate}: ${errorMessage(error)}`)
          return null
        }
      }
    }
    return null
  }

  /** Run one generation and commit every returned image as a durable attachment. */
  async function generate(input, options) {
    const withDataUrl = options?.withDataUrl === true
    const { body, model, referenceCount, seed, seedRandom, params } = buildBody(input)
    const started = Date.now()
    const json = await callApi('/images', body, { signal: options?.signal })
    const rows = Array.isArray(json?.data) ? json.data : []
    if (rows.length === 0) throw new Error('OpenRouter 未返回任何图片数据')

    const attachments = ctx.get('attachments')
    const saveToProject = await projectDirectory(options?.cwd)
    const images = []
    for (let i = 0; i < rows.length; i += 1) {
      const encoded = typeof rows[i]?.b64_json === 'string' ? rows[i].b64_json : ''
      if (encoded.length === 0) continue
      const declared = typeof rows[i]?.media_type === 'string' && rows[i].media_type.length > 0 ? rows[i].media_type : 'image/png'
      const supported = MEDIA_EXT[declared] !== undefined
      const mediaType = supported ? declared : 'image/png'
      const bytes = Buffer.from(encoded, 'base64')
      const imageName = `openrouter-${stamp()}-${i + 1}${MEDIA_EXT[mediaType]}`

      // The durable attachment is what makes the picture visible in the
      // conversation, so it is committed in both storage modes; only the
      // verbatim file copy moves with `saveDir`.
      let attachment = null
      let filePath = null
      if (attachments !== undefined && supported) {
        try {
          const saved = await attachments.saveImages([{ data: bytes, mediaType, name: imageName }])
          const ref = saved?.[0]
          if (ref) {
            attachment = {
              attachmentId: String(ref.attachmentId),
              mediaType: String(ref.mediaType),
              bytes: Number(ref.bytes),
              width: Number(ref.width),
              height: Number(ref.height),
              name: typeof ref.name === 'string' && ref.name.length > 0 ? ref.name : imageName,
            }
          }
        } catch (error) {
          console.warn(`[dsh-openrouter-imagen] saveImages failed: ${errorMessage(error)}`)
        }
      }
      if (saveToProject !== null) {
        filePath = await writeUnique(saveToProject, imageName, bytes)
      } else if (attachments !== undefined && supported) {
        try {
          const fileRef = await attachments.saveFile({ data: bytes, name: imageName })
          const located = fileRef === undefined ? undefined : attachments.fileHostPath(fileRef)
          if (typeof located === 'string' && located.length > 0) filePath = located
        } catch {
          /* a backend without verbatim file storage is not a failure of this call */
        }
      }

      const image = { name: imageName, mediaType, bytes: bytes.length, attachment, filePath }
      if (withDataUrl && bytes.length <= MAX_INLINE_BYTES) image.dataUrl = `data:${mediaType};base64,${encoded}`
      images.push(image)
    }
    if (images.length === 0) throw new Error('响应中没有可解析的图片数据（b64_json 缺失）')

    // Consumed only on success: a failed call must not silently discard the
    // image the user staged in the composer.
    pendingReferences = []

    // The workspace-relative form is what a model should quote back (a project
    // path must survive being moved); the absolute one is what opens a window.
    const workspace = typeof options?.cwd === 'string' && options.cwd.length > 0 ? options.cwd : null
    const relativeDir = saveToProject === null || workspace === null ? null : relative(workspace, saveToProject)
    const project =
      saveToProject === null
        ? null
        : { dir: saveToProject, relative: relativeDir !== null && !relativeDir.startsWith('..') ? relativeDir : saveToProject }

    const usage = json?.usage ?? null
    const cost = typeof usage?.cost === 'number' ? usage.cost : null
    // A provider that echoes the seed it used is authoritative; OpenRouter does
    // not document such a field today, so this stays a tolerant read.
    const echoed = Number(rows[0]?.seed ?? json?.seed)
    const usedSeed = Number.isFinite(echoed) ? Math.floor(echoed) : seed
    return {
      ok: true,
      model,
      prompt: body.prompt,
      referenceCount,
      images,
      project,
      cost,
      usage,
      elapsedMs: Date.now() - started,
      seed: usedSeed,
      seedRandom: usedSeed === seed && seedRandom,
      params,
    }
  }

  /* ---- model-visible tool ---- */

  /**
   * The declared parameter names, kept beside the DSL because the DSL cannot
   * close the schema root: `defineTool` emits an open object at the top level,
   * so an undeclared key is "valid" until `execute` refuses it.
   */
  const TOOL_PARAM_KEYS = new Set([
    'prompt',
    'model',
    'count',
    'resolution',
    'aspect_ratio',
    'quality',
    'background',
    'seed',
    'reference_images',
    'reference_files',
  ])

  const tool = defineTool({
    name: 'openrouter_generate_imagen',
    description:
      'Generate raster images through the OpenRouter Image API (POST /api/v1/images). 每次调用都会用你自己的 OpenRouter 额度真实计费，提示词与参考图会离开本机发往 OpenRouter —— 只在用户确实要图时调用；生成结果作为附件回到对话，并写入会话工作目录（见结果里的 保存目录）。'
      + '\n\n提示词按商业摄影的结构写：主体与动作 → 环境与道具 → 光线（主光、辅光、轮廓光、色温、时段）→ 镜头与构图（焦段、景深、机位、画幅）→ 风格与质感 → 画面中需要出现的文字（逐字给出，注明大小写与拼写）。用具体的名词和参数，不要写「高级 / 大气 / 好看」这类空词；除画面内需要中文外，英文提示词效果通常更好。'
      + '\n\n带参考图时（reference_files / reference_images）：生图模型自己会读图，提示词只写场景、风格、光线、镜头、构图和画幅，不要在文字里复述参考图里已有的产品外观（外形、颜色、logo、端子、结构）—— 那只会与图像本身冲突、降低还原度；要锁住主体就写一句「保持参考图中的产品外观不变」。用户明确要求改的地方（换装、换姿势、换背景）只写要改的那部分，其余仍用这句话锁住。'
      + '\n\n参数默认由用户的面板决定（Settings → 图像生成，以及输入框上方那条「图像」）：模型、分辨率、画幅、画质、背景、数量、种子都从面板读。只有用户在这条消息里点名了某个参数（「用 2K」「要 9:16」「出两张」「用 xxx 模型」）才传它，没点名就一律省略 —— 不要替用户挑参数，也不要为了「更合适」而覆盖他的设置；如果你认为他的要求需要某个面板没设的参数，在回复里说一句建议，而不是自己改。'
      + '\n\n调用成功后回复一句话说明结果即可：卡片已经展示了参数、种子、保存路径和费用，不要复述它们。'
      + '\n\nThe generated image comes back as a durable attachment you can see, and is written into the session workspace (see 保存目录 in the result) so later calls can read, move or embed the file. reference_files takes absolute local paths inside the session workspace (paths outside it are refused, because those bytes get uploaded to a third party); reference_images takes http(s) or data URLs. A per-call parameter overrides the composer panel for that call only — pass one only when the user asked for it in this message; the values actually sent come back in params. The API key, model and the panel defaults live in Settings → 图像生成.',
    parameters: {
      prompt: { type: 'string', required: true, description: 'The picture to create, written in the commercial-photography structure described above. With a reference image, describe only scene, style, light, lens and framing — never restate the product appearance that the reference already shows.' },
      model: { type: 'string', description: 'OpenRouter image model slug, e.g. google/gemini-2.5-flash-image. Omit unless the user asked for a specific model in this message — omitting uses the model configured in the panel.' },
      count: { type: 'integer', description: 'How many images to request (1-10). Omit unless the user explicitly asked for several variations — omitting uses 数量 from the panel, and every extra image costs money. Not every model supports more than 1.' },
      resolution: { type: 'string', enum: ['512', '1K', '2K', '4K'], description: 'Resolution tier. Omit unless the user asked for a resolution in this message — omitting uses 分辨率 from the panel.' },
      aspect_ratio: { type: 'string', description: 'Aspect ratio such as 1:1, 16:9, 9:16, 4:3, 3:4. Pass it only when the user names a ratio or a composition in this message (「9:16」「竖构图」「方图」); 主体取景（例如「全身照」）不算。Omit to use 画幅 from the panel — if the framing the user asked for seems to need a ratio the panel does not have, say so in your reply instead of overriding it; what was sent comes back in params.aspect_ratio.' },
      quality: { type: 'string', enum: ['auto', 'low', 'medium', 'high'], description: 'Quality tier where the model supports it. Omit unless the user asked for a quality in this message — omitting uses 画质 from the panel.' },
      background: { type: 'string', enum: ['auto', 'transparent', 'opaque'], description: 'Background handling where the model supports it. Omit unless the user asked for it in this message — omitting uses 背景 from the panel.' },
      seed: { type: 'integer', description: 'Fix the sampling seed to reproduce an earlier image. Omit unless the user asked to reuse or fix a seed — omitting uses 种子 from the panel, where an empty box makes the plugin draw a random one; what was sent comes back in params.seed.' },
      reference_images: { type: 'array', items: { type: 'string' }, description: 'Reference images for image-to-image: http(s) URLs or data URLs. Max 4.' },
      reference_files: { type: 'array', items: { type: 'string' }, description: 'Absolute local paths of reference images inside the session workspace (outside paths are refused); each is read and inlined as a data URL. Max 4.' },
    },
    output: {
      schema: {
        type: 'object',
        additionalProperties: true,
        properties: {
          ok: { type: 'boolean' },
          model: { type: 'string' },
          cost: { type: 'number' },
          elapsedMs: { type: 'number' },
          referenceCount: { type: 'number' },
          error: { type: 'string' },
          outputDir: { type: 'string' },
          outputDirRelative: { type: 'string' },
          seed: { type: 'number' },
          seedRandom: { type: 'boolean' },
          params: {
            type: 'object',
            additionalProperties: true,
            properties: {
              model: { type: 'string' },
              count: { type: 'number' },
              resolution: { type: 'string' },
              aspect_ratio: { type: 'string' },
              quality: { type: 'string' },
              output_format: { type: 'string' },
              background: { type: 'string' },
              seed: { type: 'number' },
              referenceCount: { type: 'number' },
            },
          },
          images: {
            type: 'array',
            items: {
              type: 'object',
              additionalProperties: true,
              properties: {
                name: { type: 'string' },
                mediaType: { type: 'string' },
                bytes: { type: 'number' },
                filePath: { type: 'string' },
                attachment: {
                  type: 'object',
                  additionalProperties: true,
                  properties: {
                    attachmentId: { type: 'string' },
                    mediaType: { type: 'string' },
                    bytes: { type: 'number' },
                    width: { type: 'number' },
                    height: { type: 'number' },
                    name: { type: 'string' },
                  },
                },
              },
            },
          },
        },
      },
      render(_args, value) {
        if (value?.ok !== true) {
          return [{ type: 'text', text: `图像生成失败：${value?.error ?? '未知错误'}` }]
        }
        const images = Array.isArray(value.images) ? value.images : []
        const parts = [`已生成 ${images.length} 张图片（模型 ${value.model}`]
        if (value.referenceCount > 0) parts.push(`，参考图 ${value.referenceCount} 张`)
        parts.push(`，耗时 ${Math.round((value.elapsedMs ?? 0) / 1000)} 秒`)
        if (typeof value.cost === 'number') parts.push(`，费用 $${value.cost.toFixed(4)}`)
        parts.push('）。')
        // The effective parameters belong on the card: the conversation model
        // cannot see the composer panel, so this line is the only place a user
        // can confirm what a call actually asked the provider for.
        const sent = value.params
        if (sent !== undefined && sent !== null) {
          const bits = []
          if (typeof sent.resolution === 'string' && sent.resolution.length > 0) bits.push(sent.resolution)
          if (typeof sent.aspect_ratio === 'string' && sent.aspect_ratio.length > 0) bits.push(sent.aspect_ratio)
          if (typeof sent.quality === 'string' && sent.quality.length > 0) bits.push(sent.quality)
          if (typeof sent.background === 'string' && sent.background !== 'auto') bits.push(`背景 ${sent.background}`)
          if (typeof sent.output_format === 'string' && sent.output_format.length > 0) bits.push(sent.output_format)
          if (typeof sent.count === 'number' && sent.count > 1) bits.push(`${sent.count} 张`)
          if (bits.length > 0) parts.push(`\n参数：${bits.join(' · ')}`)
        }
        // The directory line is what the conversation card turns into an "open
        // this folder" button; the file lines are what a later call reads.
        if (typeof value.outputDir === 'string' && value.outputDir.length > 0) parts.push(`\n保存目录：${value.outputDir}`)
        // Emitted before `文件：`, whose block is parsed as a list of paths — a
        // seed line after it would be read as one more file.
        if (typeof value.seed === 'number' && Number.isFinite(value.seed)) {
          parts.push(`\n种子：${value.seed}${value.seedRandom === true ? '（本次随机）' : ''}`)
        }
        const files = images.map((image) => image?.filePath).filter((path) => typeof path === 'string' && path.length > 0)
        if (files.length > 0) parts.push(`\n文件：${files.join('\n')}`)
        const blocks = [{ type: 'text', text: parts.join('') }]
        for (const image of images) {
          if (image?.attachment) blocks.push({ type: 'image', attachment: image.attachment })
        }
        return blocks
      },
    },
    execute: async (args, exec) => {
      try {
        // `defineTool` cannot close its own parameter root (dsh-tools builds the
        // JSON schema as an open object), so an undeclared key would pass
        // validation and be spread into the provider request. Reject it here.
        const unknown = Object.keys(args ?? {}).filter((key) => !TOOL_PARAM_KEYS.has(key))
        if (unknown.length > 0) throw new Error(`未知参数：${unknown.join('、')}；本工具只接受 ${[...TOOL_PARAM_KEYS].join('、')}`)
        // The session workspace decides both where the file goes and which local
        // paths may be read as references.
        const cwd = exec?.agent?.session?.header?.cwd
        const input = { ...args, reference_images: args?.reference_images ?? [] }
        if (Array.isArray(args?.reference_files) && args.reference_files.length > 0) {
          const inlined = await readReferenceFiles(args.reference_files, cwd, exec?.signal)
          input.reference_images = [...(input.reference_images ?? []), ...inlined]
        }
        const result = await generate(input, { withDataUrl: false, cwd, signal: exec?.signal })
        return {
          ok: true,
          model: result.model,
          prompt: result.prompt,
          referenceCount: result.referenceCount,
          seed: result.seed,
          seedRandom: result.seedRandom,
          params: result.params,
          elapsedMs: result.elapsedMs,
          ...(result.project === null ? {} : { outputDir: result.project.dir, outputDirRelative: result.project.relative }),
          ...(result.cost === null ? {} : { cost: result.cost }),
          images: result.images.map((image) => ({
            name: image.name,
            mediaType: image.mediaType,
            bytes: image.bytes,
            ...(image.filePath === null ? {} : { filePath: image.filePath }),
            ...(image.attachment === null ? {} : { attachment: image.attachment }),
          })),
        }
      } catch (error) {
        return { ok: false, error: errorMessage(error), images: [] }
      }
    },
  })
  ctx.effect(() => ctx.tools.register(tool), 'openrouter-imagen: model tool')

  /**
   * Read local reference images as data URLs.
   *
   * These bytes leave the machine for a third-party API, so a path the *model*
   * chose is confined to the session workspace: `dsh-fs-local` resolves any
   * absolute path and the fs sandbox fences writes, not reads, so without this
   * check the parameter is a read-anything-and-upload-it channel. An unreadable
   * file stays non-fatal, because one bad path should not lose the whole call.
   */
  async function readReferenceFiles(paths, cwd, signal) {
    const fs = ctx.get('fs')
    if (fs === undefined) return []
    const urls = []
    for (const raw of paths.slice(0, MAX_REFERENCES)) {
      if (typeof raw !== 'string' || raw.trim().length === 0) continue
      let target
      try {
        // `fs.resolve` returns a handle { targetKey, displayPath }, NOT a string
        // (dsh-fs-local resolveLocalTarget). `displayPath` is the absolute host
        // path; relative paths must be resolved against the session cwd so a
        // model-supplied bare name behaves like the read/write tools.
        target = await fs.resolve(raw.trim(), typeof cwd === 'string' && cwd.length > 0 ? { cwd } : {})
      } catch (error) {
        console.warn(`[dsh-openrouter-imagen] reference file failed (${raw}): ${errorMessage(error)}`)
        continue
      }
      if (typeof cwd === 'string' && cwd.length > 0) {
        const inside = relative(cwd, String(target.displayPath ?? ''))
        if (inside.startsWith('..') || isAbsolute(inside)) {
          throw new Error(`参考图必须位于会话工作目录内：${raw}（先复制进项目，或用 reference_images 传 http(s)/data URL）`)
        }
      }
      try {
        const bytes = await fs.readBytes(target, signal, 20 * 1024 * 1024)
        if (!bytes || bytes.length === 0) continue
        const lower = raw.toLowerCase()
        const mediaType = lower.endsWith('.jpg') || lower.endsWith('.jpeg') ? 'image/jpeg'
          : lower.endsWith('.webp') ? 'image/webp'
            : lower.endsWith('.gif') ? 'image/gif'
              : 'image/png'
        urls.push(`data:${mediaType};base64,${toBase64(bytes)}`)
      } catch (error) {
        console.warn(`[dsh-openrouter-imagen] reference file failed (${raw}): ${errorMessage(error)}`)
      }
    }
    return urls
  }

  /* ---- browser API route ---- */

  const readJsonBody = (req, limit = 32 * 1024 * 1024) =>
    new Promise((resolve, reject) => {
      const chunks = []
      let size = 0
      req.on('data', (chunk) => {
        size += chunk.length
        if (size > limit) {
          reject(new Error('请求体过大'))
          req.destroy()
          return
        }
        chunks.push(chunk)
      })
      req.on('end', () => {
        if (chunks.length === 0) {
          resolve({})
          return
        }
        try {
          resolve(JSON.parse(Buffer.concat(chunks).toString('utf8')))
        } catch {
          reject(new Error('请求体不是合法 JSON'))
        }
      })
      req.on('error', reject)
    })

  const sendJson = (res, status, payload) => {
    const body = JSON.stringify(payload)
    res.statusCode = status
    res.setHeader('content-type', 'application/json; charset=utf-8')
    res.setHeader('cache-control', 'no-store')
    res.end(body)
  }

  /** The config view handed to the browser: never includes the key itself. */
  const publicConfig = () => {
    const settings = readConfig()
    const config = {}
    for (const key of WRITABLE) {
      if (key === 'apiKey') continue
      config[key] = settings[key]
    }
    return { config, hasKey: String(settings.apiKey ?? '').length > 0, suggestions: SUGGESTED_MODELS, namespace: NS }
  }

  async function handleApi(req, res) {
    // The same trust fence every shipped route uses: `requestRejection` answers
    // 403 for a foreign Host/Origin and 401 without the browser's auth cookie.
    // Without it any page (or a DNS-rebinding host) could POST to /generate and
    // spend the stored key, or overwrite the settings through /config.
    const connection = ctx.get('connection')
    if (connection !== undefined && typeof connection.requestRejection === 'function') {
      const rejection = connection.requestRejection(req)
      if (rejection !== undefined) {
        sendJson(res, rejection, { ok: false, error: rejection === 401 ? '未通过浏览器鉴权，请从 DSH 窗口访问' : '该来源不被信任' })
        return
      }
    }
    const url = new URL(req.url ?? '/', 'http://127.0.0.1')
    const action = url.pathname.slice(API_PATH.length).replace(/^\/+/, '')
    const method = req.method ?? 'GET'
    try {
      if (action === 'config' && method === 'GET') {
        sendJson(res, 200, { ok: true, ...publicConfig() })
        return
      }
      if (action === 'config' && method === 'POST') {
        const patch = await readJsonBody(req)
        const next = {}
        for (const key of WRITABLE) {
          if (!Object.prototype.hasOwnProperty.call(patch, key)) continue
          if (key === 'apiKey' && String(patch.apiKey ?? '').trim().length === 0) continue
          next[key] = key === 'count' ? Number(patch[key]) : patch[key]
        }
        if (Object.keys(next).length > 0) await scope.update(next)
        sendJson(res, 200, { ok: true, ...publicConfig() })
        return
      }
      if (action === 'models' && method === 'GET') {
        const json = await callApi('/images/models', undefined, { requireKey: false })
        const models = (Array.isArray(json?.data) ? json.data : [])
          .filter((row) => typeof row?.id === 'string' && row.id.length > 0)
          .map((row) => ({ id: row.id, name: typeof row.name === 'string' && row.name.length > 0 ? row.name : row.id }))
          .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))
        sendJson(res, 200, { ok: true, models, count: models.length })
        return
      }
      if (action === 'test' && method === 'GET') {
        const json = await callApi('/key')
        const data = json?.data ?? {}
        const parts = []
        if (typeof data.label === 'string' && data.label.length > 0) parts.push(`标签：${data.label}`)
        if (data.is_free_tier === true) parts.push('免费额度账户')
        if (typeof data.usage === 'number') parts.push(`已用：$${data.usage.toFixed(4)}`)
        if (typeof data.limit === 'number') parts.push(`额度上限：$${data.limit.toFixed(2)}`)
        else if (data.limit === null) parts.push('额度上限：未设置（按量付费）')
        if (typeof data.limit_remaining === 'number') parts.push(`剩余：$${data.limit_remaining.toFixed(4)}`)
        sendJson(res, 200, { ok: true, report: parts.length > 0 ? parts.join('　·　') : JSON.stringify(data).slice(0, 300) })
        return
      }
      if (action === 'generate' && method === 'POST') {
        const input = await readJsonBody(req)
        // No `exec` here, so no session workspace: this route is for scripts and
        // the offline pre-flight, and its files stay in the attachment store.
        const result = await generate(input, { withDataUrl: true })
        sendJson(res, 200, {
          ok: true,
          model: result.model,
          prompt: result.prompt,
          referenceCount: result.referenceCount,
          seed: result.seed,
          seedRandom: result.seedRandom,
          params: result.params,
          project: result.project,
          cost: result.cost,
          elapsedMs: result.elapsedMs,
          images: result.images.map((image) => ({
            name: image.name,
            mediaType: image.mediaType,
            bytes: image.bytes,
            filePath: image.filePath,
            dataUrl: image.dataUrl ?? null,
          })),
        })
        return
      }
      // Staged reference images from the composer. GET reports only metadata —
      // the client already holds the bytes it uploaded, and echoing
      // multi-megabyte data URLs back on every poll would be wasteful.
      if (action === 'reference' && method === 'GET') {
        sendJson(res, 200, {
          ok: true,
          count: pendingReferences.length,
          references: pendingReferences.map((url) => {
            const match = /^data:([^;]+);base64,(.*)$/su.exec(url)
            const data = match?.[2] ?? ''
            return { mediaType: match?.[1] ?? 'image/png', bytes: Math.floor((data.length * 3) / 4) }
          }),
        })
        return
      }
      if (action === 'reference' && method === 'POST') {
        const payload = await readJsonBody(req)
        const incoming = Array.isArray(payload?.references) ? payload.references : []
        // Append, not replace: the client can only send the bytes it holds, so
        // a replace protocol would silently drop references staged earlier.
        const next = pendingReferences.slice()
        for (const entry of incoming) {
          if (next.length >= MAX_REFERENCES) break
          if (entry === null || typeof entry !== 'object') continue
          const data = typeof entry.data === 'string' ? entry.data : ''
          const mediaType = MEDIA_EXT[entry.mediaType] === undefined ? null : entry.mediaType
          if (data.length === 0 || mediaType === null) continue
          next.push(`data:${mediaType};base64,${data}`)
        }
        pendingReferences = next
        sendJson(res, 200, { ok: true, count: pendingReferences.length })
        return
      }
      if (action === 'reference' && method === 'DELETE') {
        pendingReferences = []
        sendJson(res, 200, { ok: true, count: 0 })
        return
      }
      sendJson(res, 404, { ok: false, error: `未知接口：${method} ${action}` })
    } catch (error) {
      sendJson(res, 200, { ok: false, error: errorMessage(error) })
    }
  }

  // The API route normally registers here, because the Web carrier is composed
  // long before this row. If it is not up yet, wait for it instead of silently
  // leaving the Settings page calling a 404.
  //
  // The service is reached through ctx.get(), never as `ctx.webServer`: this
  // plugin does not declare webServer in `inject` (declaring it would park the
  // whole plugin — tool included — on any surface without a Web carrier), and
  // an undeclared service read is rejected by the inject guard.
  const registerRoute = (service) => {
    if (service === undefined) return
    ctx.effect(() => service.register({ kind: 'prefix', path: API_PATH, handler: handleApi }), 'openrouter-imagen: api route')
  }

  const webServer = ctx.get('webServer')
  if (webServer !== undefined) registerRoute(webServer)
  else ctx.inject(['webServer'], (webCtx) => registerRoute(webCtx.get('webServer')))
}
